export const options = [
  {
    id: 'album',
    name: 'Album',
    options: [
      { value: 'tulip', label: 'Tulip', checked: false },
      { value: 'road', label: 'Road', checked: false },
      { value: 'love', label: 'Love', checked: false },
      { value: 'wedding', label: 'Wedding', checked: true },
      { value: 'game', label: 'Game', checked: false },
    ],
  },
  {
    id: 'color',
    name: 'Color',
    options: [
      { value: 'white', label: 'White', checked: false },
      { value: 'beige', label: 'Beige', checked: false },
      { value: 'blue', label: 'Blue', checked: true },
      { value: 'brown', label: 'Brown', checked: false },
      { value: 'green', label: 'Green', checked: false },
      { value: 'purple', label: 'Purple', checked: false },
    ],
  },
  {
    id: 'tag',
    name: 'Tag',
    options: [
      { value: 'new-arrivals', label: 'New Arrivals', checked: false },
      { value: 'travel', label: 'Travel', checked: true },
      { value: 'organization', label: 'Organization', checked: false },
      { value: 'accessories', label: 'Accessories', checked: false },
    ],
  }
]

export const photos = [
  {
    id: 1,
    name: 'Earthen Bottle',
    href: '#',
    album: 'Road',
    tag: 'Travel',
    color: 'Black',
    date: '2021/3/11',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-01.jpg',
    imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
  },
  {
    id: 2,
    name: 'Nomad Tumbler',
    href: '#',
    album: 'Tulip',
    tag: 'Flower',
    color: 'Red',
    date: '2021/3/11',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-02.jpg',
    imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
  },
  {
    id: 3,
    name: 'Focus Paper Refill',
    href: '#',
    album: 'Love',
    tag: 'Accessories',
    color: 'Yellow',
    date: '2021/3/11',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-03.jpg',
    imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
  },
  {
    id: 4,
    name: 'Machined Mechanical Pencil',
    href: '#',
    album: 'Road',
    tag: 'Travel',
    color: 'White',
    date: '2021/3/11',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-04.jpg',
    imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
  },
  {
    id: 5,
    name: 'Focus Card Tray',
    href: '#',
    album: 'Road',
    tag: 'Organization',
    color: 'Black',
    date: '2021/3/11',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-05.jpg',
    imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
  },
  {
    id: 6,
    name: 'Focus Multi-Pack',
    href: '#',
    album: 'Game',
    tag: 'Organization',
    color: 'White',
    date: '2021/3/11',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-06.jpg',
    imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
  },
  {
    id: 7,
    name: 'Brass Scissors',
    href: '#',
    album: 'Road',
    tag: 'Travel',
    color: 'Black',
    date: '2021/3/11',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-07.jpg',
    imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
  },
  {
    id: 8,
    name: 'Focus Carry Pouch',
    href: '#',
    album: 'Wedding',
    tag: 'Travel',
    color: 'Blue',
    date: '2021/3/11',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-08.jpg',
    imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
  }
]
